#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=16GB
#SBATCH --time=48:00:00
#SBATCH --partition=gpu
#SBATCH --gres=gpu:v100:2

module purge
module load gcc/8.3.0
module load python/3.7.6
module load cuda/10.1.243
module load cudnn/8.0.2-10.1

pip3 install torch torchvision
pip install Augmentor
pip install numpy
pip install opencv-python
python main_appnet.py